# Generated by Django 4.2.17 on 2025-05-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_baykeshopgoods_is_virtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshoporders',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='邮箱'),
        ),
    ]
