# Generated by Django 4.2.17 on 2025-05-13 13:03

from django.db import migrations

import baykeshop.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_baykeshoporders_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshopgoodssku',
            name='email_message',
            field=baykeshop.db.fields.RichTextField(blank=True, default='', verbose_name='虚拟商品邮件内容'),
        ),
    ]
