# Generated by Django 4.2.17 on 2026-04-21 05:34

from django.conf import settings
import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('shop', '0007_alter_baykeshopgoodssku_email_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaykeShopGoodsFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='是否删除')),
                ('notify_type', models.CharField(choices=[('arrival', '到货通知'), ('price_drop', '降价通知')], default='arrival', max_length=20, verbose_name='通知类型')),
                ('is_notified', models.BooleanField(default=False, verbose_name='是否已通知')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.baykeshopgoods', verbose_name='商品')),
                ('site', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '商品关注',
                'verbose_name_plural': '商品关注',
                'ordering': ['-created_time'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('current_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='BaykeShopGoodsFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='是否删除')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.baykeshopgoods', verbose_name='商品')),
                ('site', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '商品收藏',
                'verbose_name_plural': '商品收藏',
                'ordering': ['-created_time'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('current_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='baykeshopgoodsfollow',
            constraint=models.UniqueConstraint(fields=('user', 'goods', 'notify_type'), name='unique_follow'),
        ),
        migrations.AddConstraint(
            model_name='baykeshopgoodsfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'goods'), name='unique_favorite'),
        ),
    ]
