# Generated by Django 4.2.17 on 2026-04-24 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_baykeshopgoodsfollow_baykeshopgoodsfavorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshopgoodsimages',
            name='image',
            field=models.ImageField(help_text='建议尺寸: 800*800，排在第一个的图片会作为商品主图', upload_to='goods/images', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='baykeshopgoodssku',
            name='sales',
            field=models.PositiveIntegerField(default=0, verbose_name='销量'),
        ),
        migrations.AlterField(
            model_name='baykeshopgoodssku',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='baykeshopordersgoods',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='数量'),
        ),
        migrations.AddIndex(
            model_name='baykeshoporders',
            index=models.Index(fields=['status', 'created_time'], name='status_created_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='baykeshoporderscomment',
            constraint=models.UniqueConstraint(fields=('user', 'order'), name='unique_user_order_comment'),
        ),
    ]
