# Generated by Django 4.2.17 on 2026-04-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_add_trigram_index'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='baykeshoporderscomment',
            name='unique_user_order_comment',
        ),
        migrations.RemoveIndex(
            model_name='baykeshoporders',
            name='status_created_time_idx',
        ),
        migrations.AddField(
            model_name='baykeshoporders',
            name='carrier',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='快递公司'),
        ),
        migrations.AddField(
            model_name='baykeshoporders',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='运单号'),
        ),
        migrations.AlterField(
            model_name='baykeshopgoodssku',
            name='sales',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='销量'),
        ),
        migrations.AlterField(
            model_name='baykeshopgoodssku',
            name='stock',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='baykeshopordersgoods',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
    ]
