# Generated by Django 4.2.17 on 2026-04-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_add_logistics_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshoporders',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='取消原因'),
        ),
    ]
