# Generated by Django 4.2.17 on 2026-04-24 07:09

import baykeshop.contrib.system.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('system', '0002_baykemenus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykebanners',
            name='url',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='baykedictmodel',
            name='value',
            field=models.TextField(help_text='\n            布尔值：true/false;\n            键值对：key1:value1一行一对;\n            list:value1,value2一行一个值;\n            json:{"key1":"value1"}\n        ', validators=[baykeshop.contrib.system.validators.validate_dict_value], verbose_name='值'),
        ),
        migrations.AlterField(
            model_name='baykemenus',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.permission', verbose_name='权限'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'ip', 'date'), name='unique_visit_record'),
        ),
    ]
