# Generated by Django 4.2.17 on 2026-03-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_baykeshopuseraddress_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshopuser',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='邮箱验证令牌'),
        ),
        migrations.AddField(
            model_name='baykeshopuser',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='邮箱验证时间'),
        ),
        migrations.AddField(
            model_name='baykeshopuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='邮箱是否验证'),
        ),
    ]
