# Generated by Django 4.2.17 on 2026-03-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_add_ip_security_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshopuser',
            name='verification_token_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='验证令牌生成IP'),
        ),
        migrations.AddField(
            model_name='baykeshopuser',
            name='last_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后发送验证邮件时间'),
        ),
        migrations.AddField(
            model_name='baykeshopuser',
            name='verification_attempts',
            field=models.IntegerField(default=0, verbose_name='验证尝试次数'),
        ),
    ]
