# Generated by Django 4.2.17 on 2026-03-15 02:36

import django.contrib.sites.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_add_security_fields'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='securitylog',
            managers=[
                ('current_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name='baykeshopuser',
            name='email_verify_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='邮箱验证令牌生成时间'),
        ),
    ]
