# Generated by Django 4.2.17 on 2026-04-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_add_email_verify_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshopuser',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
